# Filterbank config
filterbank:
  fb_name: stft
  n_filters: 32
  kernel_size: 32
  stride: 16
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
  mask_input: reim
  mask_output: reim
# Training config
training:
  epochs: 100
  batch_size: 8
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: data/wav16k/min/tr/
  valid_dir: data/wav16k/min/cv/
  task: sep_reverb
  nondefault_nsrc:
  sample_rate: 16000
  mode: min
  segments: 4.0
